kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-user-clutser-role
rules:
- apiGroups: [""]
  resources: ["services", "services/proxy"]
  verbs: ["get", "watch", "list", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-user-clutser-role-binding
subjects:
- kind: User
  name: lambda-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lambda-user-clutser-role
  apiGroup: rbac.authorization.k8s.io
